before_script:
  - npm install mocha chai nyc
  - npm install nyc codecov coveralls
  - psql -c 'create database wayfarerTest;' -U postgres
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
services:
  - postgresql
after_success:
  - npm run coverage

