insert into trips (bus_id, origin, destination, trip_date, fare, status) values (1, 'Lae', 'Laurel', '8/13/2018', '128.03', 'cancelled');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (2, 'Lazaro Cardenas', 'Menomonie', '7/25/2018', '97.36', 'cancelled');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (3, 'Santa Cruz', 'Darwin', '5/24/2019', '88.44', 'cancelled');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (4, 'Huangcun', 'Gale', '7/13/2018', '70.59', 'active');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (5, 'Dankama', 'Burning Wood', '7/15/2018', '143.90', 'active');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (6, 'Houzhai', 'Bay', '10/19/2018', '161.10', 'cancelled');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (7, 'Salam', 'Towne', '3/18/2019', '125.85', 'cancelled');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (8, 'Kyoto', 'Elmside', '2/14/2019', '101,72', 'cancelled');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (9, 'Maurisu', 'Bluestem', '5/28/2019', '170.01', 'cancelled');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (10, 'Ayagoz', 'American', '11/17/2018', '62.56', 'cancelled');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (11, 'Rerawere', 'Hoepker', '11/2/2018', '30.44', 'active');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (12, 'Grybów', 'Veith', '8/9/2018', '143,58', 'active');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (13, 'Banjar Bengkelgede', 'Esker', '3/26/2019', '58.37', 'active');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (14, 'Eirado', 'Clarendon', '10/19/2018', '109.12', 'cancelled');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (15, 'Attard', 'Artisan', '8/29/2018', '119,54', 'cancelled');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (16, 'Inđija', 'Canary', '11/6/2018', '153.75', 'cancelled');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (17, 'Chico', 'Forest Run', '1/12/2019', '88,28', 'cancelled');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (18, 'Rengang', 'Stone Corner', '10/21/2018', '114.57', 'active');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (19, 'Ridder', 'Mandrake', '8/13/2018', '199.01', 'active');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (20, 'Vrachnaíika', 'Bonner', '1/26/2019', '136.35', 'cancelled');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (21, 'Ya’ergenchu', 'Claremont', '11/16/2018', '81.32', 'cancelled');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (22, 'Xiguantun Muguzu Manzuxiang', 'Eliot', '4/4/2019', '31.76', 'active');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (23, 'Huangascar', 'Donald', '1/18/2019', '106.79', 'active');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (24, 'Três Lagoas', 'Graceland', '6/16/2019', '185.73', 'cancelled');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (25, 'Sabnie', 'Towne', '2/14/2019', '187.42', 'active');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (26, 'Agusan', 'Chinook', '2/15/2019', '120.00', 'cancelled');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (27, 'Sanom', 'Mesta', '12/7/2018', '102.76', 'active');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (28, 'Paradahan', 'Lotheville', '7/25/2018', '30.05', 'active');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (29, 'Boshkengash', 'Magdeline', '9/5/2018', '35,37', 'active');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (30, 'Golmud', 'Warbler', '3/27/2019', '91.84', 'cancelled');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (31, 'Zhishan', 'Crest Line', '12/23/2018', '128,82', 'cancelled');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (32, 'Banjar Gunungpande', 'Farmco', '10/11/2018', '94.96', 'active');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (33, 'Ngetkib', 'Victoria', '7/2/2018', '31,52', 'active');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (34, 'Cawalo', 'Rutledge', '10/3/2018', '47.82', 'active');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (35, 'Anton', 'Amoth', '4/5/2019', '75.76', 'active');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (36, 'Saint Petersburg', 'Banding', '10/28/2018', '101.40', 'active');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (37, 'Petrodvorets', 'Twin Pines', '7/21/2018', '86,51', 'active');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (38, 'Niejiahe', 'Talisman', '10/16/2018', '174,18', 'cancelled');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (39, 'Cimanggu', 'Bluejay', '7/29/2018', '169.18', 'active');
insert into trips (bus_id, origin, destination, trip_date, fare, status) values (40, 'Santo Tomas', 'Montana', '3/29/2019', '31,35', 'cancelled');
